queue_rules:
  - name: duplicated default from Automatic merge on approval (main)
    queue_conditions:
      - and:
          - "base=main"
          - "#review-threads-unresolved=0"
          - "#approved-reviews-by>=1"
          - "#changes-requested-reviews-by=0"
          - "label!=do-not-merge"
          - "label!=mergify-ignore"
          - "check-success=ci/circleci: plugins-tests"
          - "check-success=ci/circleci: contracts-tests"
          - "check-success=ci/circleci: core-tests"
          - "check-success=ci/circleci: demo-tests"
          - "check-success=ci/circleci: executor-tests"
          - "check-success=ci/circleci: yarn-monorepo"
          - "check-success=license/cla"
    merge_conditions: []
    merge_method: merge
  - name: duplicated default from Automatic merge on approval (develop)
    queue_conditions:
      - and:
          - "base=develop"
          - "#review-threads-unresolved=0"
          - "#approved-reviews-by>=1"
          - "#changes-requested-reviews-by=0"
          - "label!=do-not-merge"
          - "label!=mergify-ignore"
          - "check-success=ci/circleci: plugins-tests"
          - "check-success=ci/circleci: contracts-tests"
          - "check-success=ci/circleci: core-tests"
          - "check-success=ci/circleci: demo-tests"
          - "check-success=ci/circleci: executor-tests"
          - "check-success=ci/circleci: yarn-monorepo"
          - "check-success=license/cla"
    merge_conditions: []
    merge_method: squash

pull_request_rules:
  - name: Add merge train label
    conditions:
      - "queue-position >= 0"
    actions:
      comment:
        message: |
          This PR has been added to the merge queue, and will be merged soon.
      label:
        add:
          - on-merge-train

  - name: Remove merge train label
    conditions:
      - "queue-position = -1"
    actions:
      label:
        remove:
          - on-merge-train

  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: Hey @{{author}}! This PR has merge conflicts. Please fix them before continuing review.
      label:
        add:
          - conflict

  - name: Remove conflicts label when conflicts gone
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: Notify author when added to merge queue
    conditions:
      - "check-pending=Queue: Embarked in merge train"
    actions:
      comment:
        message: |
          This PR is next in line to be merged, and will be merged as soon as checks pass.

  - name: Notify author when merge queue failed
    conditions:
      - "check-failure=Queue: Embarked in merge train"
    actions:
      comment:
        message: |
          Merge failed. Please see automated check logs for more details.

  - name: Nag changesets
    conditions:
      - and:
          - 'files~=\.((?<!\.spec\.)ts|js|sol)$'
          - '-files~=^\.changeset/(.*)\.md'
    actions:
      comment:
        message: |
          This PR changes implementation code, but doesn't include a changeset. Did you forget to add one?
  - name: Automatic merge on approval (develop) + Automatic merge on approval (main)
    conditions: []
    actions:
      queue:
