export type SupportedNetwork = {
  name: string
  displayName: string
  chainId: bigint
  rpcUrl: () => string
  etherscan: {
    apiURL: string
    browserURL: string
    envKey: string
    blockExplorer: BlockExplorer
  }
  currency: string
  dripSize: string
  requiredEnvVariables: Array<string>
  networkType: NetworkType
  dripVersion: number
  decimals: number
  queryFilterBlockLimit: number
  legacyTx: boolean
  actionGasLimitBuffer: boolean
  useHigherMaxGasLimit: boolean
  rollupStack?: {
    provider: RollupProvider
    type: RollupType
  }
}

export type SupportedLocalNetwork = {
  name: string
  chainId: bigint
  networkType: NetworkType
  legacyTx: false
  actionGasLimitBuffer: false
  useHigherMaxGasLimit: false
}

export const SPHINX_LOCAL_NETWORKS: Array<SupportedLocalNetwork> = [
  {
    name: 'anvil',
    chainId: BigInt(31337),
    networkType: 'Local',
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
]

type BlockExplorer = 'Etherscan' | 'Blockscout' | 'Unsupported'
type NetworkType = 'Testnet' | 'Mainnet' | 'Local'
type RollupProvider = 'Conduit' | 'Caldera'
type RollupType = 'OP Stack' | 'Arbitrum'

export const SPHINX_NETWORKS: Array<SupportedNetwork> = [
  {
    name: 'ethereum',
    displayName: 'Ethereum',
    chainId: BigInt(1),
    rpcUrl: () =>
      `https://eth-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api.etherscan.io/api',
      browserURL: 'https://etherscan.io',
      envKey: 'ETH_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.15',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'sepolia',
    displayName: 'Sepolia',
    chainId: BigInt(11155111),
    rpcUrl: () =>
      `https://eth-sepolia.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api-sepolia.etherscan.io/api',
      browserURL: 'https://sepolia.etherscan.io',
      envKey: 'ETH_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.15',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'optimism',
    displayName: 'Optimism',
    chainId: BigInt(10),
    rpcUrl: () =>
      `https://opt-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api-optimistic.etherscan.io/api',
      browserURL: 'https://optimistic.etherscan.io/',
      envKey: 'OPT_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.025',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'optimism_sepolia',
    displayName: 'Optimism Sepolia',
    chainId: BigInt(11155420),
    rpcUrl: () =>
      `https://opt-sepolia.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api-sepolia-optimism.etherscan.io/api',
      browserURL: 'https://sepolia-optimism.etherscan.io/',
      envKey: 'OPT_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.15',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'arbitrum',
    displayName: 'Arbitrum',
    chainId: BigInt(42161),
    rpcUrl: () =>
      `https://arb-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api.arbiscan.io/api',
      browserURL: 'https://arbiscan.io/',
      envKey: 'ARB_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.025',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'arbitrum_sepolia',
    displayName: 'Arbitrum Sepolia',
    chainId: BigInt(421614),
    rpcUrl: () =>
      `https://arb-sepolia.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api-sepolia.arbiscan.io/api',
      browserURL: 'https://sepolia.arbiscan.io/',
      envKey: 'ARB_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.15',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'polygon',
    displayName: 'Polygon',
    chainId: BigInt(137),
    rpcUrl: () =>
      `https://polygon-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api.polygonscan.com/api',
      browserURL: 'https://polygonscan.com',
      envKey: 'POLYGON_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'MATIC',
    dripSize: '1',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'polygon_mumbai',
    displayName: 'Polygon Mumbai',
    chainId: BigInt(80001),
    rpcUrl: () =>
      `https://polygon-mumbai.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api-testnet.polygonscan.com/api',
      browserURL: 'https://mumbai.polygonscan.com/',
      envKey: 'POLYGON_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'MATIC',
    dripSize: '0.15',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'bnb',
    displayName: 'Binance Smart Chain',
    chainId: BigInt(56),
    rpcUrl: () => process.env.BNB_MAINNET_URL!,
    etherscan: {
      apiURL: 'https://api.bscscan.com/api',
      browserURL: 'https://bscscan.com',
      envKey: 'BNB_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'BNB',
    dripSize: '0.05',
    requiredEnvVariables: ['BNB_MAINNET_URL'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'bnb_testnet',
    displayName: 'Binance Smart Chain Testnet',
    chainId: BigInt(97),
    rpcUrl: () => process.env.BNB_TESTNET_URL!,
    etherscan: {
      apiURL: 'https://api-testnet.bscscan.com/api',
      browserURL: 'https://testnet.bscscan.com',
      envKey: 'BNB_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'BNB',
    dripSize: '0.15',
    requiredEnvVariables: ['BNB_TESTNET_URL'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'gnosis',
    displayName: 'Gnosis',
    chainId: BigInt(100),
    rpcUrl: () => process.env.GNOSIS_MAINNET_URL!,
    etherscan: {
      apiURL: 'https://api.gnosisscan.io/api',
      browserURL: 'https://gnosisscan.io',
      envKey: 'GNOSIS_MAINNET_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'xDAI',
    dripSize: '1',
    requiredEnvVariables: ['GNOSIS_MAINNET_URL'],
    networkType: 'Mainnet',
    dripVersion: 1,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'gnosis_chiado',
    displayName: 'Gnosis Chiado',
    chainId: BigInt(10200),
    rpcUrl: () => process.env.CHIADO_RPC_URL!,
    etherscan: {
      apiURL: 'https://gnosis-chiado.blockscout.com/api',
      browserURL: 'https://gnosis-chiado.blockscout.com',
      envKey: 'GNOSIS_CHIADO_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'xDAI',
    dripSize: '0.15',
    requiredEnvVariables: ['CHIADO_RPC_URL'],
    networkType: 'Testnet',
    dripVersion: 1,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'linea',
    displayName: 'Linea',
    chainId: BigInt(59144),
    rpcUrl: () =>
      `https://linea-mainnet.infura.io/v3/${process.env.INFURA_API_KEY}`,
    etherscan: {
      apiURL: 'https://api.lineascan.build/api',
      browserURL: 'https://lineascan.build',
      envKey: 'LINEA_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.025',
    requiredEnvVariables: ['INFURA_API_KEY'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'linea_goerli',
    displayName: 'Linea Goerli',
    chainId: BigInt(59140),
    rpcUrl: () =>
      `https://linea-goerli.infura.io/v3/${process.env.INFURA_API_KEY}`,
    etherscan: {
      apiURL: 'https://api-goerli.lineascan.build/api',
      browserURL: 'https://goerli.lineascan.build',
      envKey: 'LINEA_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.15',
    requiredEnvVariables: ['INFURA_API_KEY'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'polygon_zkevm',
    displayName: 'Polygon zkEVM',
    chainId: BigInt(1101),
    rpcUrl: () => process.env.POLYGON_ZKEVM_MAINNET_URL!,
    etherscan: {
      apiURL: 'https://api-zkevm.polygonscan.com/api',
      browserURL: 'https://zkevm.polygonscan.com/',
      envKey: 'POLYGON_ZKEVM_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.025',
    requiredEnvVariables: ['POLYGON_ZKEVM_MAINNET_URL'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'polygon_zkevm_goerli',
    displayName: 'Polygon zkEVM Goerli',
    chainId: BigInt(1442),
    rpcUrl: () => process.env.POLYGON_ZKEVM_TESTNET_URL!,
    etherscan: {
      apiURL: 'https://api-testnet-zkevm.polygonscan.com/api',
      browserURL: 'https://testnet-zkevm.polygonscan.com',
      envKey: 'POLYGON_ZKEVM_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.15',
    requiredEnvVariables: ['POLYGON_ZKEVM_TESTNET_URL'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'avalanche',
    displayName: 'Avalanche',
    chainId: BigInt(43114),
    rpcUrl: () =>
      `https://avalanche-mainnet.infura.io/v3/${process.env.INFURA_API_KEY}`,
    etherscan: {
      apiURL: 'https://api.snowtrace.io/api',
      browserURL: 'https://snowtrace.io/',
      envKey: 'AVAX_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'AVAX',
    dripSize: '1',
    requiredEnvVariables: ['INFURA_API_KEY'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'avalanche_fuji',
    displayName: 'Avalanche Fuji',
    chainId: BigInt(43113),
    rpcUrl: () =>
      `https://avalanche-fuji.infura.io/v3/${process.env.INFURA_API_KEY}`,
    etherscan: {
      apiURL: 'https://api-testnet.snowtrace.io/api',
      browserURL: 'https://testnet.snowtrace.io/',
      envKey: 'AVAX_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'AVAX',
    dripSize: '1',
    requiredEnvVariables: ['INFURA_API_KEY'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'fantom',
    displayName: 'Fantom',
    chainId: BigInt(250),
    rpcUrl: () => process.env.FANTOM_MAINNET_RPC_URL!,
    etherscan: {
      apiURL: 'https://api.ftmscan.com/api',
      browserURL: 'https://ftmscan.com',
      envKey: 'FANTOM_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'FTM',
    dripSize: '1',
    requiredEnvVariables: ['FANTOM_MAINNET_RPC_URL'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'fantom_testnet',
    displayName: 'Fantom Testnet',
    chainId: BigInt(4002),
    rpcUrl: () => process.env.FANTOM_TESTNET_RPC_URL!,
    etherscan: {
      apiURL: '',
      browserURL: '',
      envKey: '',
      blockExplorer: 'Unsupported',
    },
    currency: 'FTM',
    dripSize: '1',
    requiredEnvVariables: ['FANTOM_TESTNET_RPC_URL'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'base',
    displayName: 'Base',
    chainId: BigInt(8453),
    rpcUrl: () =>
      `https://base-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://api.basescan.org/api',
      browserURL: 'https://basescan.org/',
      envKey: 'BASE_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.025',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'base_sepolia',
    displayName: 'Base Sepolia',
    chainId: BigInt(84532),
    rpcUrl: () =>
      `https://base-sepolia.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    etherscan: {
      apiURL: 'https://base-sepolia.blockscout.com/api',
      browserURL: 'https://base-sepolia.blockscout.com/',
      envKey: 'BASE_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'ETH',
    dripSize: '0.15',
    requiredEnvVariables: ['ALCHEMY_API_KEY'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'celo',
    displayName: 'Celo',
    chainId: BigInt(42220),
    rpcUrl: () =>
      `https://celo-mainnet.infura.io/v3/${process.env.INFURA_API_KEY}`,
    etherscan: {
      apiURL: 'https://api.celoscan.io/api',
      browserURL: 'https://celoscan.io/',
      envKey: 'CELO_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'CELO',
    dripSize: '1',
    requiredEnvVariables: ['INFURA_API_KEY'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'celo_alfajores',
    displayName: 'Celo Alfajores',
    chainId: BigInt(44787),
    rpcUrl: () =>
      `https://celo-alfajores.infura.io/v3/${process.env.INFURA_API_KEY}`,
    etherscan: {
      apiURL: 'https://api-alfajores.celoscan.io/api',
      browserURL: 'https://alfajores.celoscan.io/',
      envKey: 'CELO_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'CELO',
    dripSize: '0.15',
    requiredEnvVariables: ['INFURA_API_KEY'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'moonriver',
    displayName: 'Moonriver',
    chainId: BigInt(1285),
    rpcUrl: () => process.env.MOONRIVER_RPC_URL!,
    etherscan: {
      apiURL: 'https://api-moonriver.moonscan.io/api',
      browserURL: 'https://moonriver.moonscan.io',
      envKey: 'MOONRIVER_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'MOVR',
    dripSize: '0.15',
    requiredEnvVariables: ['MOONRIVER_RPC_URL'],
    queryFilterBlockLimit: 500,
    dripVersion: 0,
    networkType: 'Mainnet',
    decimals: 18,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'moonbeam',
    displayName: 'Moonbeam',
    chainId: BigInt(1284),
    rpcUrl: () => process.env.MOONBEAM_RPC_URL!,
    etherscan: {
      apiURL: 'https://api-moonbeam.moonscan.io/api',
      browserURL: 'https://moonbeam.moonscan.io',
      envKey: 'MOONBEAM_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'GLMR',
    dripSize: '1',
    requiredEnvVariables: ['MOONBEAM_RPC_URL'],
    queryFilterBlockLimit: 500,
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'moonbase_alpha',
    displayName: 'Moonbase Alpha',
    chainId: BigInt(1287),
    rpcUrl: () => process.env.MOONBASE_ALPHA_RPC_URL!,
    etherscan: {
      apiURL: 'https://api-moonbase.moonscan.io/api',
      browserURL: 'https://moonbase.moonscan.io/',
      envKey: 'MOONBEAM_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'GLMR',
    dripSize: '0.05',
    requiredEnvVariables: ['MOONBASE_ALPHA_RPC_URL'],
    queryFilterBlockLimit: 500,
    networkType: 'Testnet',
    dripVersion: 1,
    decimals: 18,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'fuse',
    displayName: 'Fuse',
    chainId: BigInt(122),
    rpcUrl: () => process.env.FUSE_RPC_URL!,
    etherscan: {
      apiURL: 'https://explorer.fuse.io/api',
      browserURL: 'https://explorer.fuse.io',
      envKey: 'FUSE_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'FUSE',
    dripSize: '1',
    requiredEnvVariables: ['FUSE_RPC_URL'],
    networkType: 'Mainnet',
    dripVersion: 0,
    legacyTx: true,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'evmos',
    displayName: 'Evmos',
    chainId: BigInt(9001),
    rpcUrl: () => process.env.EVMOS_RPC_URL!,
    etherscan: {
      // Need to support sourcify
      apiURL: '',
      browserURL: '',
      envKey: '',
      blockExplorer: 'Unsupported',
    },
    currency: 'EVMOS',
    dripSize: '1',
    requiredEnvVariables: ['EVMOS_RPC_URL'],
    dripVersion: 0,
    networkType: 'Mainnet',
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'evmos_testnet',
    displayName: 'Evmos Testnet',
    chainId: BigInt(9000),
    rpcUrl: () => process.env.EVMOS_TESTNET_RPC_URL!,
    etherscan: {
      // Need to support sourcify
      apiURL: '',
      browserURL: '',
      envKey: '',
      blockExplorer: 'Unsupported',
    },
    currency: 'EVMOS',
    dripSize: '0.01',
    requiredEnvVariables: ['EVMOS_TESTNET_RPC_URL'],
    networkType: 'Testnet',
    dripVersion: 1,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'kava',
    displayName: 'Kava',
    chainId: BigInt(2222),
    rpcUrl: () => process.env.KAVA_RPC_URL!,
    etherscan: {
      apiURL: 'https://kavascan.com/api',
      browserURL: 'https://kavascan.com',
      envKey: 'KAVA_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'KAVA',
    dripSize: '1',
    requiredEnvVariables: ['KAVA_RPC_URL'],
    dripVersion: 0,
    networkType: 'Mainnet',
    legacyTx: true,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'kava_testnet',
    displayName: 'Kava Testnet',
    chainId: BigInt(2221),
    rpcUrl: () => process.env.KAVA_TESTNET_RPC_URL!,
    etherscan: {
      // Need to support sourcify
      // They have blockscout, but the api is non-responsive
      apiURL: '',
      browserURL: '',
      envKey: '',
      blockExplorer: 'Unsupported',
    },
    currency: 'KAVA',
    dripSize: '1',
    requiredEnvVariables: ['KAVA_TESTNET_RPC_URL'],
    networkType: 'Testnet',
    dripVersion: 0,
    legacyTx: true,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
  },
  {
    name: 'oktc',
    displayName: 'OKT Chain',
    chainId: BigInt(66),
    rpcUrl: () => process.env.OKTC_RPC_URL!,
    etherscan: {
      apiURL: '',
      browserURL: '',
      envKey: '',
      blockExplorer: 'Unsupported',
    },
    currency: 'OKT',
    dripSize: '1',
    requiredEnvVariables: ['OKTC_RPC_URL'],
    dripVersion: 1,
    queryFilterBlockLimit: 500,
    networkType: 'Mainnet',
    legacyTx: true,
    decimals: 18,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: true,
  },
  {
    name: 'scroll',
    displayName: 'Scroll',
    chainId: BigInt(534352),
    rpcUrl: () => process.env.SCROLL_RPC_URL!,
    etherscan: {
      apiURL: 'https://api.scrollscan.com/api',
      browserURL: 'https://scrollscan.com/',
      envKey: 'SCROLL_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.025',
    requiredEnvVariables: ['SCROLL_RPC_URL'],
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: true,
  },
  {
    name: 'scroll_sepolia',
    displayName: 'Scroll Sepolia',
    chainId: BigInt(534351),
    rpcUrl: () => process.env.SCROLL_TESTNET_RPC_URL!,
    etherscan: {
      apiURL: 'https://api-sepolia.scrollscan.com/api',
      browserURL: 'https://sepolia.scrollscan.com/',
      envKey: 'SCROLL_ETHERSCAN_API_KEY',
      blockExplorer: 'Etherscan',
    },
    currency: 'ETH',
    dripSize: '0.15',
    requiredEnvVariables: ['SCROLL_TESTNET_RPC_URL'],
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: true,
  },
  {
    name: 'rootstock',
    displayName: 'Rootstock',
    chainId: BigInt(30),
    rpcUrl: () => process.env.ROOTSTOCK_RPC_URL!,
    etherscan: {
      apiURL: 'https://rootstock.blockscout.com/api',
      browserURL: 'https://rootstock.blockscout.com/',
      envKey: 'ROOTSTOCK_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'RBTC',
    dripSize: '0.001',
    requiredEnvVariables: ['ROOTSTOCK_RPC_URL'],
    dripVersion: 2,
    networkType: 'Mainnet',
    legacyTx: true,
    decimals: 8,
    queryFilterBlockLimit: 2000,
    actionGasLimitBuffer: true,
    useHigherMaxGasLimit: true,
  },
  {
    name: 'rootstock_testnet',
    displayName: 'Rootstock Testnet',
    chainId: BigInt(31),
    rpcUrl: () => process.env.ROOTSTOCK_TESTNET_RPC_URL!,
    etherscan: {
      apiURL: 'https://rootstock.blockscout.com/api',
      browserURL: 'https://rootstock.blockscout.com/',
      envKey: 'ROOTSTOCK_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'RBTC',
    dripSize: '0.001',
    requiredEnvVariables: ['ROOTSTOCK_RPC_URL'],
    dripVersion: 2,
    networkType: 'Testnet',
    legacyTx: true,
    decimals: 8,
    queryFilterBlockLimit: 2000,
    actionGasLimitBuffer: true,
    useHigherMaxGasLimit: true,
  },
  {
    name: 'zora',
    displayName: 'Zora',
    chainId: BigInt(7777777),
    rpcUrl: () => process.env.ZORA_RPC_URL!,
    etherscan: {
      apiURL: 'https://explorer.zora.energy/api',
      browserURL: 'https://explorer.zora.energy/',
      envKey: 'ZORA_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'ETH',
    dripSize: '0.025',
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
    requiredEnvVariables: ['ZORA_RPC_URL'],
    rollupStack: {
      provider: 'Conduit',
      type: 'OP Stack',
    },
  },
  {
    name: 'zora_sepolia',
    displayName: 'Zora Sepolia',
    chainId: BigInt(999999999),
    rpcUrl: () => process.env.ZORA_SEPOLIA_RPC_URL!,
    etherscan: {
      apiURL: 'https://sepolia.explorer.zora.energy/api',
      browserURL: 'https://sepolia.explorer.zora.energy/',
      envKey: 'ZORA_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'ETH',
    dripSize: '0.15',
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
    requiredEnvVariables: ['ZORA_SEPOLIA_RPC_URL'],
    rollupStack: {
      provider: 'Conduit',
      type: 'OP Stack',
    },
  },
  {
    name: 'rari',
    displayName: 'RARI',
    chainId: BigInt(1380012617),
    rpcUrl: () => process.env.RARI_RPC_URL!,
    etherscan: {
      apiURL: 'https://mainnet.explorer.rarichain.org/api',
      browserURL: 'https://mainnet.explorer.rarichain.org/',
      envKey: 'RARI_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'ETH',
    dripSize: '0.025',
    networkType: 'Mainnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
    requiredEnvVariables: ['RARI_RPC_URL'],
    rollupStack: {
      provider: 'Caldera',
      type: 'Arbitrum',
    },
  },
  {
    name: 'rari_sepolia',
    displayName: 'RARI Sepolia',
    chainId: BigInt(1918988905),
    rpcUrl: () => process.env.RARI_SEPOLIA_RPC_URL!,
    etherscan: {
      apiURL: 'https://explorer.rarichain.org/api',
      browserURL: 'https://explorer.rarichain.org/',
      envKey: 'RARI_ETHERSCAN_API_KEY',
      blockExplorer: 'Blockscout',
    },
    currency: 'ETH',
    dripSize: '0.15',
    networkType: 'Testnet',
    dripVersion: 0,
    decimals: 18,
    queryFilterBlockLimit: 2000,
    legacyTx: false,
    actionGasLimitBuffer: false,
    useHigherMaxGasLimit: false,
    requiredEnvVariables: ['RARI_SEPOLIA_RPC_URL'],
    rollupStack: {
      provider: 'Caldera',
      type: 'Arbitrum',
    },
  },
]
