// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// SPDX-License-Identifier: MIT
pragma solidity >=0.7.4 <0.9.0;

import { Sphinx } from "@sphinx-labs/plugins/Sphinx.sol";
import { AbstractContractClient } from "@sphinx-labs/plugins/AbstractContractClient.sol";

contract ExecutorTestClient is AbstractContractClient {
  constructor(address _sphinxManager, address _sphinx, address _impl) AbstractContractClient(_sphinxManager, _sphinx, _impl) {}

  fallback() external override {
    require(msg.sender != sphinxInternalManager, "Attempted to call a non-existent function on ExecutorTestClient. Did you try to call a view function from your Sphinx deploy function? View functions are not currently supported in the deploy function.");
    _delegate(sphinxInternalImpl);
  }

  
}

